name: "Helm Unit Tests"
description: "Run Helm chart unit tests with quintush/helm-unittest"

branding:
  icon: check-square
  color: green

inputs:
  flags:
    description: "Flags to pass to helm unittest"
    required: false
    default: "-3 --color"

  charts:
    description: "Charts to run tests for, separated by spaces"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        installScript=https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        curl "$installScript" 2>/dev/null | bash >/dev/null
      shell: bash

    - run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest >/dev/null 2>/dev/null
      shell: bash

    - run: |
        tr ' ' '\n' <<< "${{ inputs.charts }}" | grep -v '^$' > charts-to-test || true
        find . -type f -name 'Chart.yaml' -exec dirname {} \; > all-charts
        [ -z "${{ inputs.charts }}" ] && mv all-charts charts-to-test || true
      shell: bash

    - run: |
        for chart in $(cat charts-to-test); do
          helm dependency update "$chart" >/dev/null
        done
      shell: bash

    - run: helm unittest ${{ inputs.flags }} $(cat charts-to-test)
      shell: bash
